
USE master
GO
IF DB_ID('VOUCHER')IS NOT NULL
	DROP DATABASE VOUCHER
GO
CREATE DATABASE VOUCHER

go
USE VOUCHER
GO

CREATE TABLE DOANH_NGHIEP
(
idDN VARCHAR(10) NOT NULL,
tenDN NVARCHAR(200),
sdtDN NVARCHAR(20),
diaChiDN NVARCHAR(200),

PRIMARY KEY (idDN)
)

go
CREATE TABLE HOP_DONG
(
idHD VARCHAR(10) NOT NULL,
maHD VARCHAR(10),
ngayKiHD DATETIME,
ngayBatDauHD DATETIME,
ngayKetThucHD DATETIME,

idDN VARCHAR(10),

PRIMARY KEY(idHD)
)

go
CREATE TABLE SAN_PHAM_QUANG_CAO
(
idSP VARCHAR(10) NOT NULL,
tenQuangCao NVARCHAR(200),
tinhTrang INT,
soPhieuToiThieuBanRa INT,
tiLeGiaoTanNha_TrucTruyen float,
soPhieuToiThieuGiaoTanNha int,
thoiGianBatDauQC datetime,
thoiGianKetThucQC datetime,

idHD varchar(10),

PRIMARY KEY (idSP)
)

go
CREATE TABLE DIEU_KIEN_TIEN_QUYET
(
idDKTQ VARCHAR(10),
toanTu NVARCHAR(50),
tenQuanHe VARCHAR(100),
tenThuocTinh VARCHAR(100),
giaTri NVARCHAR(100),
kieuDuLieu VARCHAR(50),

idSP varchar(10),

PRIMARY KEY (idDKTQ)
)

go
CREATE TABLE THONG_TIN_SAN_PHAM
(
idTTSP VARCHAR(10),
tenSanPham NVARCHAR(200),
hinhAnh NVARCHAR(1000),
diemNoiBat NVARCHAR(1000),
thongTinChiTiet NVARCHAR(1000),
tenLinhVuc NVARCHAR(1000),

PRIMARY KEY (idTTSP)
)

go
CREATE TABLE TTSP_SAN_PHAM_QUANG_CAO
(
idSP VARCHAR(10),
tenQuangCao NVARCHAR(200),
giaGoc INT,
giaBan INT,
soPhieuThanhToan INT,
soPhieuDuocMua INT,
dieuKienApDung text,
diaDiemApDung text,
thoiGianBatDauSD datetime,
thoiGianKetThucSD datetime,
hinhAnh NVARCHAR(1000),
diemNoiBat NVARCHAR(1000),
thongTinChiTiet NVARCHAR(1000),
tenLinhVuc NVARCHAR(1000),

idTTSP VARCHAR(10),

PRIMARY KEY (idSP)
)

go
CREATE TABLE TTSL_SAN_PHAM_QUANG_CAO
(
idSP VARCHAR(10),
soLuongSP INT,
soLuongTon INT,

PRIMARY KEY (idSP)
)

go
CREATE TABLE VOUCHER
(
idVC VARCHAR(10),
maSoVoucher VARCHAR(10),

idSP VARCHAR(10),

PRIMARY KEY (idVC)
) 

CREATE TABLE THANH_VIEN
(
idTV VARCHAR(10),
emailTV NVARCHAR(50),
hoTenTV NVARCHAR(100),
taiKhoan INT,
sdtTV NVARCHAR(30),

PRIMARY KEY (idTV)
)

CREATE TABLE THE_NAP
(
matMa VARCHAR(10),
soSeri VARCHAR(10),
menhGia INT,

idTV VARCHAR(10),

PRIMARY KEY (matMa, soSeri)
)

go
 CREATE TABLE HOADON_PHIEUGH
 (
 idPGH VARCHAR(10),
maSoHD VARCHAR(10),
ngayLapHD DATETIME,
giaTriHD INT,
maSoPhieu VARCHAR(10),
trangThai INT,
thoiGianGiaoHang DATETIME,

idVC VARCHAR(10),
idTV VARCHAR(10),

PRIMARY KEY (idPGH)
 )
 
 go
 CREATE TABLE GIAO_DICH_TRUC_TUYEN
 (
idPGH VARCHAR(10),
tenNguoiGui NVARCHAR(100),
mua_tang bit,
loiNhan text,
tenNN nvarchar(100),
sdtNN varchar(30),
emailNN varchar(50),

PRIMARY KEY (idPGH)
 )
 
 GO
 CREATE TABLE GIAO_DICH_TAN_NHA 
 (
 idPGH VARCHAR(10),
 tenNguoiNhan NVARCHAR(50),
 sdtNguoiNhan VARCHAR(30),
 diaChiGiao NVARCHAR(100),
 thoiGianBatDauNhan DATETIME,
 thoiGianKetThucNhan DATETIME,
 ngayNhanHang DATETIME,
 loiNhanMuaVoucher TEXT,
 
 PRIMARY KEY (idPGH)
 )
 
ALTER TABLE dbo.HOP_DONG
ADD CONSTRAINT FK_HOPDONG_DOANHNGHIEP
FOREIGN KEY (idDN)
REFERENCES dbo.DOANH_NGHIEP(idDN)

GO
ALTER TABLE dbo.SAN_PHAM_QUANG_CAO
ADD CONSTRAINT FK_SPQC_HOPDONG
FOREIGN KEY (idHD)
REFERENCES dbo.HOP_DONG(idHD)

GO
ALTER TABLE dbo.TTSL_SAN_PHAM_QUANG_CAO
ADD CONSTRAINT FK_TTSLQPQC_SPQC
FOREIGN KEY (idSP)
REFERENCES dbo.SAN_PHAM_QUANG_CAO(idSP)

GO
ALTER TABLE dbo.TTSP_SAN_PHAM_QUANG_CAO
ADD CONSTRAINT FK_TTSPSPQC_TTSP
FOREIGN KEY (idTTSP)
REFERENCES dbo.THONG_TIN_SAN_PHAM(idTTSP),
CONSTRAINT FK_TTSPQC_SPQC
FOREIGN KEY (idSP)
REFERENCES dbo.SAN_PHAM_QUANG_CAO(idSP)

GO
ALTER TABLE dbo.DIEU_KIEN_TIEN_QUYET
ADD CONSTRAINT FK_DKTQ_SPQC
FOREIGN KEY (idSP)
REFERENCES dbo.SAN_PHAM_QUANG_CAO(idSP)

GO
ALTER TABLE dbo.VOUCHER 
ADD CONSTRAINT FK_VOUCHER_SPQC
FOREIGN KEY (idSP)
REFERENCES dbo.SAN_PHAM_QUANG_CAO(idSP)

GO
ALTER TABLE dbo.THE_NAP 
ADD CONSTRAINT FK_THENAP_THANHVIEN
FOREIGN KEY(idTV)
REFERENCES dbo.THANH_VIEN(idTV)

GO
ALTER TABLE dbo.HOADON_PHIEUGH
ADD CONSTRAINT FK_HDPGH_VOUCHER
FOREIGN KEY (idVC)
REFERENCES dbo.VOUCHER (idVC),
CONSTRAINT FK_HDPGH_THANHVIEN
FOREIGN KEY (idTV)
REFERENCES dbo.THANH_VIEN(idTV)

GO
ALTER TABLE dbo.GIAO_DICH_TRUC_TUYEN
ADD CONSTRAINT FK_GDTT_HDPGH
FOREIGN KEY (idPGH)
REFERENCES dbo.HOADON_PHIEUGH(idPGH)

GO
ALTER TABLE dbo.GIAO_DICH_TAN_NHA
ADD CONSTRAINT FK_GDTN_HDPGH
FOREIGN KEY (idPGH)
REFERENCES dbo.HOADON_PHIEUGH(idPGH)