USE master
GO
IF DB_ID('VOUCHERDB') IS NOT NULL
	DROP DATABASE VOUCHERDB
GO
CREATE DATABASE VOUCHERDB

GO
USE VOUCHERDB

GO
CREATE TABLE HOPDONG_DOANHNGHIEP
(
maHD VARCHAR(10) NOT NULL,
ngayKiHD DATETIME NOT NULL,
ngayBatDauHD DATETIME NOT NULL,
ngayKetThucHD DATETIME NOT NULL,
tenDoanhNghiep NVARCHAR(50) NOT	NULL,
sdtDN VARCHAR(15) NOT NULL,
diaChiDN NVARCHAR(50) NOT NULL,

PRIMARY KEY (maHD)
)

GO 
CREATE TABLE SAN_PHAM_QUANG_CAO
(
maQC INT NOT NULL,
soLuongSP INT NOT NULL,
soLuongTon INT NOT NULL,
soPhieuToiThieuBanRa INT NOT NULL,
tiLeGiaoTanNha FLOAT NOT NULL,
soPhieuToiThieuGiaoTanNha INT NOT NULL,
tinhTrang INT NOT NULL,
thoiGianBatDauQC DATETIME NOT NULL,
thoiGianKetThucQC DATETIME NOT NULL,
maHD VARCHAR(10) NOT NULL,

PRIMARY KEY (maQC)
)

GO
CREATE TABLE THONG_TIN_QUANG_CAO
(
maQC INT NOT NULL,
tenQuangCao NVARCHAR(50) NOT NULL,
giaGoc INT NOT null, 
giaBan INT NOT NULL, 
soPhieuThanhToan INT NOT NULL,
soPhieuDuocMua INT NOT NULL,
dieuKienApDung TEXT NOT NULL,
diaDiemApDung NVARCHAR(100) NOT NULL,
thoiGianBatDauSD DATETIME NOT NULL,
thoiGianKetThucSD DATETIME NOT NULL,

maSP INT NOT NULL,
tenSanPham NVARCHAR(50) NOT NULL,
hinhAnh	VARCHAR(50) NOT NULL,
diemNoiBat NVARCHAR(50) NOT NULL,
thongTinChiTiet NVARCHAR(50) NOT NULL,
tenLinhVuc NVARCHAR(50) NOT NULL,

PRIMARY KEY (maQC)
)

GO
CREATE TABLE SO_LUONG_QUANG_CAO
(
maQC INT NOT NULL,
soLuongSP INT NOT NULL,
soLuongTon INT NOT NULL,

PRIMARY KEY (maQC)
)

GO
CREATE TABLE DIEU_KIEN_TIEN_QUYET
(
maDK INT NOT NULL,
tenQuanHe VARCHAR(50) NOT NULL,
tenThuocTinh VARCHAR(50) NOT NULL,
toanTu VARCHAR(50) NOT NULL,
kieuDuLieu VARCHAR(50) NOT NULL,
giaTri TEXT NOT NULL,

maQC int NOT NULL,

PRIMARY KEY (maDK)
)

GO
CREATE TABLE THANH_VIEN
(
maTV INT NOT NULL,
emailTV VARCHAR(50) NOT NULL,
hoTenTV VARCHAR(50) NOT NULL,
sdTV VARCHAR(50),
taiKhoanThe INT NOT NULL,

PRIMARY KEY (maTV)
)

GO
CREATE TABLE THE_NAP
(
matMa VARCHAR(50) NOT NULL,
soSeri VARCHAR(50) NOT NULL,
menhGia FLOAT NOT NULL,
maTV INT NOT NULL,

PRIMARY KEY (matMa, soSeri)
)

GO
CREATE TABLE HOADON_PHIEUGH
(
maSoHoaDon INT NOT NULL,
ngayLapHD DATETIME NOT NULL,
giaTriHD INT NOT NULL,

maSoPhieu VARCHAR(10) UNIQUE NOT NULL,
thoiGianGiaoHang DATETIME,
loaiGiaoDich INT NOT NULL,
tinhTrang INT NOT NULL,

maTV INT NOT NULL,

PRIMARY KEY (maSoHoaDon)
)

GO
CREATE TABLE VOUCHER
(
maVoucher INT NOT NULL,
maQC int NOT NULL,
maSoHoaDon int NOT NULL,

PRIMARY KEY (maVoucher)
)

GO
CREATE TABLE GIAO_DICH_TAN_NHA
(
maSoPhieu VARCHAR(10) NOT NULL,
tenNguoiNhan NVARCHAR(100) NOT NULL,
sdtNguoiNhan VARCHAR(15) NOT NULL,
diaChiGiao NVARCHAR(100) NOT NULL,
thoiGianBatDauNhan DATETIME NOT NULL,
thoiGianKetThucNhan DATETIME NOT NULL,
ngayNhanHang DATETIME NOT NULL,
loiNhanMuaVoucher NVARCHAR(150) ,

PRIMARY KEY (maSoPhieu)
)

go	
CREATE TABLE GIAO_DICH_TRUC_TUYEN
(
maSoPhieu VARCHAR(10) NOT NULL,
laPhieuTang BIT NOT NULL,
tenNguoiGui NVARCHAR(100),
tenNguoiNhan NVARCHAR(100),
emailNgoiNhan NVARCHAR(100),
sdtNguoiNhan VARCHAR(15),
loiNhan NVARCHAR(150),

PRIMARY KEY (maSoPhieu)
)

go
ALTER TABLE dbo.HOPDONG_DOANHNGHIEP
ADD CONSTRAINT CK_HDDN_ThoiHanHD
CHECK (ngayBatDauHD <= ngayKetThucHD),
CONSTRAINT CK_HDDN_NgayKiHD_NgayBatDauHD
CHECK (ngayKiHD <= ngayBatDauHD)

GO
ALTER TABLE dbo.SAN_PHAM_QUANG_CAO
ADD CONSTRAINT FK_SPQC_HDDN
FOREIGN KEY (maHD)
REFERENCES dbo.HOPDONG_DOANHNGHIEP(maHD),
CONSTRAINT CK_SPQC_SoPhieuToiThieuGiaoTanNha
CHECK (soPhieuToiThieuGiaoTanNha >= 1),
CONSTRAINT CK_SPQC_TinhTrang
CHECK (tinhTrang IN (1, 2, 3)),
CONSTRAINT CK_SPQC_ThoiGianQC
CHECK (thoiGianBatDauQC < thoiGianKetThucQC),
CONSTRAINT CK_SPQC_SoPhieuToiThieuBanRa
CHECK (soPhieuToiThieuBanRa > 0)

go
ALTER TABLE dbo.THONG_TIN_QUANG_CAO
ADD CONSTRAINT FK_TTQC_SPQC
FOREIGN KEY (maQC)
REFERENCES dbo.SAN_PHAM_QUANG_CAO (maQC),
CONSTRAINT CK_TTQC_Gia
CHECK (giaGoc > giaBan AND giaBan >=0 AND giaGoc >= 0),
CONSTRAINT CK_TTQC_ThoiGianSD
CHECK (thoiGianBatDauSD <= thoiGianKetThucSD)

go
ALTER TABLE dbo.SO_LUONG_QUANG_CAO
ADD CONSTRAINT FK_SLQC_SPQC
FOREIGN KEY (maQC)
REFERENCES dbo.SAN_PHAM_QUANG_CAO(maQC),
CONSTRAINT CK_SLQC_SLSP_SLTon
CHECK (soLuongSP >= soLuongTon AND soLuongSP > 0  AND soLuongTon >=0)

go
ALTER TABLE dbo.THANH_VIEN
ADD CONSTRAINT CK_THANHVIEN_TaiKhoanThe
CHECK (taiKhoanThe >=0)


GO
ALTER TABLE dbo.THE_NAP
ADD CONSTRAINT FK_THENAP_THANHVIEN
FOREIGN KEY (maTV)
REFERENCES dbo.THANH_VIEN(maTV),
CONSTRAINT CK_THENAP_MenhGia
CHECK (MenhGia > 0)

go
ALTER TABLE dbo.HOADON_PHIEUGH
ADD CONSTRAINT FK_HDPGH_THANHVIEN
FOREIGN KEY (maTV)
REFERENCES dbo.THANH_VIEN(maTV),
CONSTRAINT CK_HDPGH_TinhTrang
CHECK (tinhTrang IN (1,2,3)) ,
CONSTRAINT CK_HDPGH_GiaTriHD
CHECK (giaTriHD >=0)

go
ALTER TABLE dbo.VOUCHER
ADD CONSTRAINT FK_VOUCHER_SPQC
FOREIGN KEY (maQC)
REFERENCES dbo.SAN_PHAM_QUANG_CAO(maQC),
CONSTRAINT FK_VOUCHER_HDPGH
FOREIGN KEY (maSoHoaDon) 
REFERENCES dbo.HOADON_PHIEUGH(maSoHoaDon)

GO
ALTER TABLE dbo.GIAO_DICH_TAN_NHA
ADD CONSTRAINT FK_GDTN_HDPGH
FOREIGN KEY (maSoPhieu)
REFERENCES dbo.HOADON_PHIEUGH(maSoPhieu),
CONSTRAINT CK_GDTN_ThoiGianNhan
CHECK (thoiGianBatDauNhan <= thoiGianKetThucNhan)

go
ALTER TABLE dbo.GIAO_DICH_TRUC_TUYEN
ADD CONSTRAINT FK_GDTT_HDPGH
FOREIGN KEY (maSoPhieu)
REFERENCES dbo.HOADON_PHIEUGH(maSoPhieu)

GO
ALTER TABLE dbo.DIEU_KIEN_TIEN_QUYET
ADD CONSTRAINT FK_DKTQ_SPQC
FOREIGN KEY (maQC)
REFERENCES SAN_PHAM_QUANG_CAO (maQC)